### ISSUE TITLE
npx dalai server works first time. next time having issue

### ISSUE THREAD

**Issue by manirajanvn** [cocktailpeanut/dalai#110]
Hello,

Have WIndows 10. It works first time and after restart the system, tried npx dalai serve. It requires to install dalai 

`npx dalai serve
Need to install the following packages:
  dalai
Ok to proceed? (y)`

it tries to install and stops

![image](https://user-images.githubusercontent.com/46883859/226160805-4ef5e564-d88a-43db-90e8-22fa57559924.png)

Does anyone had this issue

**Comment by tjohnman** [comment]
I had this happen and got around it by installing dalai globally. If you're OK with that: `npm i -g dalai`.

**Comment by manirajanvn** [comment]
I tried solution from https://github.com/cocktailpeanut/dalai/issues/110

It worked after these steps
Removed npm and npm cache form ....\AppData\Roaming
_npm install -g npm@latest
npx dalai serve --home C:\Users\<system name>\dalai_
