### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by RoBorg** [cocktailpeanut/dalai#130]
Having a Dockerfile would make this easier to get running.

https://github.com/cocktailpeanut/dalai/pull/129

**Comment by markusobermaier96** [comment]
that would be awesome

**Comment by pierow2k** [comment]
Looks like @metrafonic added a `Dockerfile` and `docker-compose.yml` today via [61e2d20](https://github.com/cocktailpeanut/dalai/commit/61e2d20be64fc2cfa3691c72258e88afa7eed475)

**Comment by markusobermaier96** [comment]
Nice! Thanks @metrafonic and @pierow2k for mentioning

**Comment by RoBorg** [comment]
Done in #229
