### ISSUE TITLE
Failed to build, Visual Studio problem.

### ISSUE THREAD

**Issue by edemir206** [cocktailpeanut/dalai#131]
When I try the command "npx dalai alpaca install" it gives me the error below, followed the tutorial, installed visual studio 2022 with all components, tried with command "npm config set msvs_version 2022" but did'nt help.

Does anyone know what to do ?

gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2022
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "D:\Microsoft Visual Studio\2022\Community"
gyp ERR! find VS checking VS2017 (15.9.33423.255) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS - "2017"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS

**Comment by edemir206** [comment]
Reinstalled visual studio with requirements and now ir works.

**Comment by aamiraym** [comment]
(node:14952) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\libnpx\package.json' of 'test/util/npx-bin.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

I'm getting this message while installing alpaca model library, can anybody help?
