### ISSUE TITLE
Error after i try to make "npx dalai install 7B", after the "try pulling"

### ISSUE THREAD

**Issue by SimoGiuffrida** [cocktailpeanut/dalai#137]
![image](https://user-images.githubusercontent.com/93772564/226218537-b93f29a0-2f8a-465f-bbf6-e4f91bd215c5.png)
This is the problem i get

**Comment by bradharms** [comment]
Sync tools like OneDrive occasionally interfere with Git; it's not something like that is it? (probably not but if all else fails...)

**Comment by zdrummon** [comment]
How did you end up resolving this?

**Comment by SimoGiuffrida** [comment]
> 

I installed the new version of the repo and it worked for me
