### ISSUE TITLE
Using the torrent file for installation

### ISSUE THREAD

**Issue by a7maadf** [cocktailpeanut/dalai#152]
Hello,
I have downloaded the 7B files through the published magnet and wanted to run it on alpaca, so I went to cmd and used the command `npx dalai alpaca install 7B` but I found that it started downloading the file again, however the file download was very slow so I decided to stop the download --> went to `C:\Users\{User}\dalai\alpaca\models\7B` and simply deleted the partially downloaded `.bin` file and pasted the 7B files there. I then run `npx dalai serve` and by running I got the following error

```
Server running on http://localhost:3000/
> query: {
  seed: -1,
  threads: 4,
  n_predict: 200,
  top_k: 40,
  top_p: 0.9,
  temp: 0.1,
  repeat_last_n: 64,
  repeat_penalty: 1.3,
  debug: true,
  models: [],
  prompt: 'hello',
  id: null
}
C:\Users\{User}\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:159
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (C:\Users\{User}\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:159:35)
    at Socket.<anonymous> (C:\Users\{User}\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:413:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\{User}\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\{User}\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
``` 

So I wanted to ask, is there a current fix for this? I saw you mentioning a fix in #120 by using the torrent so I'd a appreciate giving me some help here

Thank you

**Comment by AusPrinzip** [comment]
I am exactly in the same position. The package downloader is too slow.
