### ISSUE TITLE
Web UI shows multiple models but only alpaca.7B working

### ISSUE THREAD

**Issue by Nabeelhasan** [cocktailpeanut/dalai#158]
I have downloaded alpaca.7b,llama.7b and llama.13b but I am getting results only for alpaca.7b. The web UI returns nothing when llama 7b or 13b is selected.

**Comment by spacepirate0001** [comment]
Did you download the 13b model? Any errors in terminal?

**Comment by noonesaid** [comment]
Having the same issue. Only Alpaca works, none of the Llama models work. I'm getting this error when in debug mode:

`[2J[m[HWindows PowerShell

Copyright (C) Microsoft Corporation. All rights reserved.



Try the new cross-platform PowerShell https://aka.ms/pscore6]0;C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe[?25h[25l[6;1H[?25hPS C:\Users\ham\dalai\llama> [?25l
PS C:\Users\ham\dalai\llama> [93mC:\Users\ham\dalai\llama\build\Release\main[m [90m--seed[m -1 [90m--threads[m [97m4[m [90m--n_predict[m [97m200[m [90m--model[m models/13B/ggml-model-q4_0.bin [90m--top_k[m [97m40[m [90m--top_p[m [97m0.9[m [90m--temp[m [97m0.1[m [90m--repeat_last_n[m [97m

64[m [90m--repeat_penalty[m [97m1.3[m [90m-p[m [36m"how much wood can a woodchuck"[m[K

[?25h[91mC:\Users\ham\dalai\llama\build\Release\main : The term 'C:\Users\ham\dalai\llama\build\Release\main' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the [m[91m

spelling of the name, or if a path was included, verify that the path is correct and try again.[m[22X[91m

At line:1 char:1[m[101X[91m

+ C:\Users\ham\dalai\llama\build\Release\main --seed -1 --threads 4 --n ...[m[42X[91m

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[72X[91m

    + CategoryInfo          : ObjectNotFound: (C:\Users\ham\da...ld\Release\main:String) [], CommandNotFoundException

    + FullyQualifiedErrorId : CommandNotFoundException[m[63X[91m

 [m[116X

PS C:\Users\ham\dalai\llama> [92mexit[m[84X
`

**Comment by noonesaid** [comment]
I found another thread that fixed the issue for me so far :https://github.com/cocktailpeanut/dalai/issues/147

Go into  \build\Release\llama.exe and rename llama.exe to main.exe

**Comment by lisa-ee** [comment]
Installed on Win11, I have all four models running (and providing pretty horrible answers so far - ChatGPT4 keeps snickering).

**Comment by Nabeelhasan** [comment]
> Did you download the 13b model? Any errors in terminal?

**Comment by Nabeelhasan** [comment]
> Did you download the 13b model? Any errors in terminal?

I installed 13b, the download stopped twice for some reason but it downloaded without any error the third time.

**Comment by Nabeelhasan** [comment]
> I found another thread that fixed the issue for me so far :#147
> 
> Go into \build\Release\llama.exe and rename llama.exe to main.exe

Thanks, This solution worked for me.
