### ISSUE TITLE
Incredibly long 7B download

### ISSUE THREAD

**Issue by SimoGiuffrida** [cocktailpeanut/dalai#159]
Hi guys, im having a problem when downloading 7B model :
![image](https://user-images.githubusercontent.com/93772564/226446698-0ef588fd-4038-426b-b006-e1cb26033fce.png)
It is stuck in 8% of download for like 8 hours now, i have got very slow internet connection, so i dont know if it is just normal, or not.

**Comment by Natedeploys** [comment]
Yeah i'm exactly at this step for 2 hours now too

**Comment by noonesaid** [comment]
This happened to me as well. Stop the download by pressing ctrl+c, and start it again. You may also try restarting your computer.

**Comment by DiegoDG-01** [comment]
I had an issue where the download speed slowed down when my computer's monitor turned off due to inactivity.

I recommend not using the PC, going to > Settings > System > Power & sleep > When plugged in, turn off my screen after> Never and start download again.
