### ISSUE TITLE
'dalai' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by PR0M3TH3AN** [cocktailpeanut/dalai#167]
I keep getting this error after runing the install command in CMD. The correct Python and Node are installed. Windows 11. 

C:\Users\adamb>npx dalai alpaca install 7B
'dalai' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Ueraven** [comment]
Same error after several installing attempts, after following all the procedures I get:
'dalai' is not recognized as an internal or external command,
operable program or batch file.

windows powershell says I have installed Python and node

**Comment by mooggsentry** [comment]
same error here

**Comment by mooggsentry** [comment]
The issue was fixed for me in #232

**Comment by Ueraven** [comment]
> The issue was fixed for me in #232

Thanks a lot, followed the instruction, finally able to download it, my problem now is that when I open in in local host 3000 there's no model loaded to choose on for working.

**Comment by Aestheticus42** [comment]
> > The issue was fixed for me in #232
> 
> Thanks a lot, followed the instruction, finally able to download it, my problem now is that when I open in in local host 3000 there's no model loaded to choose on for working.

I had the same issue. Once I installed it using the command `npm install dalai alpaca 7b`, I then was able to _actually_ install it using the `npx dalai alpaca install 7B`. My /dalai/alpaca folder was empty before running the npx install. Also if you're using Firefox, try Edge. Others have had issues with Firefox.

**Comment by Ueraven** [comment]
> > > The issue was fixed for me in #232
> > 
> > 
> > Thanks a lot, followed the instruction, finally able to download it, my problem now is that when I open in in local host 3000 there's no model loaded to choose on for working.
> 
> I had the same issue. Once I installed it using the command `npm install dalai alpaca 7b`, I then was able to _actually_ install it using the `npx dalai alpaca install 7B`. My /dalai/alpaca folder was empty before running the npx install. Also if you're using Firefox, try Edge. Others have had issues with Firefox.

Thanks for your advice, I followed your recomendations, and now it seems to work (it's giving me wonky text most of the time), I will be testing it until I obtain the desired results.
BTW It seems to work in Opera without much fuss.
