### ISSUE TITLE
Llama 7B and 13B Issue

### ISSUE THREAD

**Issue by RIAZAHAMMED** [cocktailpeanut/dalai#169]
I really don't know what's going on here.. but see this 

`C:\Users\Riaz\dalai>npx` dalai llama install 7B 13B
mkdir C:\Users\Riaz\dalai
{ method: 'install', callparams: [ '7B', '13B' ] }
mkdir C:\Users\Riaz\dalai\llama
try fetching C:\Users\Riaz\dalai\llama https://github.com/candywrap/llama.cpp.git
[E] Pull MissingNameError: No name was provided for author in the argument or in the .git/config file.
    at Object.pull (C:\Users\Riaz\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\isomorphic-git\index.cjs:11683:24)
    at async Dalai.add (C:\Users\Riaz\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:274:7)
    at async Dalai.install (C:\Users\Riaz\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:227:7) {
  caller: 'git.pull',
  code: 'MissingNameError',
  data: { role: 'author' }
}
try cloning C:\Users\Riaz\dalai\llama https://github.com/candywrap/llama.cpp.git
next llama [AsyncFunction: make]
make
exec: mkdir build in C:\Users\Riaz\dalai\llama
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Riaz\dalai\llama> mkdir build
mkdir : An item with the specified name C:\Users\Riaz\dalai\llama\build already exists.
At line:1 char:1
+ mkdir build
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\Users\Riaz\dalai\llama\build:String) [New-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand

PS C:\Users\Riaz\dalai\llama> exit
# EXIT { exitCode: 0, signal: undefined }
exec: Remove-Item -path C:\Users\Riaz\dalai\llama\build\CMakeCache.txt in C:\Users\Riaz\dalai\llama
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Riaz\dalai\llama> Remove-Item -path C:\Users\Riaz\dalai\llama\build\CMakeCache.txt
PS C:\Users\Riaz\dalai\llama> exit
# EXIT { exitCode: 0, signal: undefined }
exec: C:\Users\Riaz\dalai\venv\Scripts\cmake .. in C:\Users\Riaz\dalai\llama\build
# data
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6
# data

# data PS C:\Users\Riaz\dalai\llama\build>
# data
# data C:\Users\Riaz\dalai\venv\Scripts\cmake ..

# data -- Building for: Visual Studio 17 2022

# data -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.

# data -- The C compiler identification is MSVC 19.35.32215.0

# data -- The CXX compiler identification is MSVC 19.35.32215.0

# data -- Detecting C compiler ABI info

# data -- Detecting C compiler ABI info - done

# data -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped

# data -- Detecting C compile features

# data -- Detecting C compile features - done

# data -- Detecting CXX compiler ABI info

# data -- Detecting CXX compiler ABI info - done

# data -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done

PS C:\Users\Riaz\dalai\llama\build> C:\Users\Riaz\dalai\venv\Scripts\cmake ..
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.35.32215.0
-- The CXX compiler identification is MSVC 19.35.32215.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- Configuring done (12.9s)
-- Generating done (0.4s)
-- Build files have been written to: C:/Users/Riaz/dalai/llama/build
PS C:\Users\Riaz\dalai\llama\build> exit

# EXIT { exitCode: 0, signal: undefined }
exec: C:\Users\Riaz\dalai\venv\Scripts\cmake --build . --config Release in C:\Users\Riaz\dalai\llama\build
# data
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6
# data

# data PS C:\Users\Riaz\dalai\llama\build>
# data
# data C:\Users\Riaz\dalai\venv\Scripts\cmake --build . --config Release

# data MSBuild version 17.5.0+6f08c67f3 for .NET Framework

# data

# data   ggml.vcxproj -> C:\Users\Riaz\dalai\llama\build\Release\ggml.lib

# data   llama.vcxproj -> C:\Users\Riaz\dalai\llama\build\Release\llama.exe

# data   quantize.vcxproj -> C:\Users\Riaz\dalai\llama\build\Release\quantize.exe

# data PS C:\Users\Riaz\dalai\llama\build>
KILL2
# data exit

# EXIT { exitCode: 0, signal: undefined }
Download model 7B
checklist.chk 100%[========================================================================================>] done
params.json 100%[==========================================================================================>] done
consolidated.00.pth 100%[==================================================================================>] done
ERROR AxiosError: connect ETIMEDOUT *********
    at AxiosError.from (C:\Users\Riaz\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\axios\dist\node\axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (C:\Users\Riaz\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\axios\dist\node\axios.cjs:2973:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (C:\Users\Riaz\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  port: 443,
  address: '***************',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -4039,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'https://agi.gpt4.org/llama/LLaMA/tokenizer_checklist.chk',
    method: 'get',
    responseType: 'stream',
    onDownloadProgress: [Function: onDownloadProgress],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/llama/LLaMA/tokenizer_checklist.chk',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'agi.gpt4.org',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/llama/LLaMA/tokenizer_checklist.chk'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /llama/LLaMA/tokenizer_checklist.chk HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: agi.gpt4.org\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/llama/LLaMA/tokenizer_checklist.chk',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'agi.gpt4.org',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://agi.gpt4.org/llama/LLaMA/tokenizer_checklist.chk',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ETIMEDOUT ********
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4039,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '************',
    port: 443
  }
}

C:\Users\Riaz\dalai>

Now this timeout happened after nearly 40 mins of downloading 
The question now is.. Is there anyone out there who got this working? In That case, what are the actual steps that works? This is a goose chase that is going no where.

**Comment by ImLunaHey** [comment]
Please add a [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) around this so it can be read.

**Comment by RIAZAHAMMED** [comment]
> Please add a [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) around this so it can be read.

My Apologies, I was not aware of that.

**Comment by ImLunaHey** [comment]
@RIAZAHAMMED you can edit the original post to add it.

**Comment by RIAZAHAMMED** [comment]
This whole thing happened because of IPV6 If it occurs to you please turn it off and restart your internet. It will work.
