### ISSUE TITLE
Error: Could not find any Visual Studio installation to use

### ISSUE THREAD

**Issue by mitsko** [cocktailpeanut/dalai#178]
When I run "npm install dalai", I get an error:
1662 verbose node v18.15.0
1663 verbose npm  v7.22.0
1664 error code 1
1665 error path c:\Program Files (x86)\Microsoft Visual Studio\2022\node_modules\node-pty
1666 error command failed
1667 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js
1668 error gyp info it worked if it ends with ok
1668 error gyp info using node-gyp@7.1.2
1668 error gyp info using node@18.15.0 | win32 | x64
1668 error gyp info find Python using Python version 3.9.12 found at "C:\Python39\python.exe"
1668 error gyp ERR! find VS
1668 error gyp ERR! find VS msvs_version was set from command line or npm config
1668 error gyp ERR! find VS - looking for Visual Studio version 2017
1668 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
1668 error gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
1668 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
1668 error gyp ERR! find VS looking for Visual Studio 2015
1668 error gyp ERR! find VS - not found
1668 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
1668 error gyp ERR! find VS
1668 error gyp ERR! find VS valid versions for msvs_version:
1668 error gyp ERR! find VS
1668 error gyp ERR! find VS **************************************************************
1668 error gyp ERR! find VS You need to install the latest version of Visual Studio
1668 error gyp ERR! find VS including the "Desktop development with C++" workload.
1668 error gyp ERR! find VS For more information consult the documentation at:
1668 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
1668 error gyp ERR! find VS **************************************************************
1668 error gyp ERR! find VS
1668 error gyp ERR! configure error
1668 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
1668 error gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
1668 error gyp ERR! stack     at C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
1668 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
1668 error gyp ERR! stack     at C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
1668 error gyp ERR! stack     at C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
1668 error gyp ERR! stack     at C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
1668 error gyp ERR! stack     at C:\Users\m.mitsko\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
1668 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
1668 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
1668 error gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
1668 error gyp ERR! System Windows_NT 10.0.19045
"Visual Studio is definitely installed (reinstalled from scratch)."
What could be the problem?

**Comment by MuraliPrasanth2** [comment]
Did you installed Install **Visual Studio 2017 or newer**? Also check if you installed it with **Desktop development with C++** workload.

Also make sure to set set the environment variable **VCINSTALLDIR** to the path of the Visual C++ installation directory. example path would be **C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC** but path may differ in your system.

And then close all the cmd and poswershell and try to run the **npm install dalai** in a new cmd again.

**Comment by mitsko** [comment]
> Did you installed **Visual Studio 2017 or newer**? Also check if you installed it with **Desktop development with C++** workload.
> 
> Also make sure to set set the environment variable **VCINSTALLDIR** to the path of the Visual C++ installation directory. example path would be **C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC** but path may differ in your system.
> 
> And then close all the cmd and poswershell and try to run the **npm install dalai** in a new cmd again.

Thank you. The solution in https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md helped.
