### ISSUE TITLE
How to uninstall a model?

### ISSUE THREAD

**Issue by MuraliPrasanth2** [cocktailpeanut/dalai#180]
I installed 7b model using the below command.

```
npm run dalai llama install 7B
```

I had the below in package.json

```
{
  "scripts": {
    "dalai": "dalai"
  },
  "dependencies": {
    "dalai": "^0.2.50"
  }
}

```

Could anyone add instruction for uninstalling a model in readme.md

**Comment by ilyhalight** [comment]
> Simply delete the folder `/home/<USER>/dalai/llama/models/7B`.

Path for windows:
`C:\Users\<USER>\dalai\llama\models\7B`

**Comment by MuraliPrasanth2** [comment]
Thank you :)

**Comment by MuraliPrasanth2** [comment]
Thank you 👍

**Comment by ibehnam** [comment]
> Simply delete the folder `/home/<USER>/dalai/llama/models/7B`.

It's actually `~/dalai` on macOS.

**Comment by willianmendesf** [comment]
thanks.

**Comment by hanebuechenes** [comment]
This doesnt work. Still it wants to take the 7B..

"File does not exist: 7B. Try "dalai llama get 7B" first."

**Comment by illusion2000** [comment]
run this on terminal 
ollama rm llama2
