### ISSUE TITLE
Unable to change thread count

### ISSUE THREAD

**Issue by Lolagatorade** [cocktailpeanut/dalai#185]
Added --thread 12 but the default says it's 4 not even 8 as said on the documentation. 

Wondering if this will help with generation speed. Hopefully soon implementation of GPU acceleration will be implemented just without eating up vram keep it on ram 🫣
![image](https://user-images.githubusercontent.com/42100725/226651719-ceea1f13-39b6-4030-b654-5b1dc123eb6c.jpeg)

**Comment by elijahvest** [comment]
![image](https://user-images.githubusercontent.com/25613081/226779545-108ea9ce-ec73-4c3a-9385-936d9c145c79.png)
I found a hacky fix by adding another div block with the input tagged as "threads."
Now the page looks like
![image](https://user-images.githubusercontent.com/25613081/226779809-196ce0e5-57f3-4315-a008-a68d1b0dda3c.png)
What my CLI shows
![image](https://user-images.githubusercontent.com/25613081/226779915-28aef104-daf5-4767-b666-bc38c070258c.png)

**Comment by elijahvest** [comment]
I haven't quite found where in the source to permanently add this, I used good ol' f12.

**Comment by elijahvest** [comment]
Found it! dalai\bin\web\views\index.ejs
line 129 add "threads"
![image](https://user-images.githubusercontent.com/25613081/226803130-64bca9c3-64ab-4134-8b83-362d46324724.png)

**Comment by keldenl** [comment]
if you're on the newest version thread should show up as  a parameter by default now!
