### ISSUE TITLE
Model not running

### ISSUE THREAD

**Issue by robonrrd** [cocktailpeanut/dalai#195]
I've followed your instructions and get no errors or warnings, but nothing is served:
```
% npx dalai llama install 7B
Need to install the following packages:
  dalai@0.2.50
Ok to proceed? (y) y
% npx dalai serve
Need to install the following packages:
  dalai@0.2.50
Ok to proceed? (y) y
%
```
Nothing exists at either `localhost` or `127.0.0.1`. 

I am on Ubuntu 22.04 with software versiosns:
```
$ node -v; npx -v
v18.15.0
9.5.0
```

**Comment by LTstrange** [comment]
me too

**Comment by robonrrd** [comment]
The commands above must be run as root.

**Comment by ruxiz2020** [comment]
same problem happened to me, I have not figured it out yet.

**Comment by robonrrd** [comment]
@ruxiz2020  I found that:
```
sudo npx dalai llama install 7B
sudo npx dalai serve
```
worked for me.
