### ISSUE TITLE
Discord channel link directs people to Breadboard instead of Dalai 

### ISSUE THREAD

**Issue by Harvester62** [cocktailpeanut/dalai#204]
The Discord link in the main page of this repository is directing people to the Breadboard Discord channel instead of the Dalai's dedicated channel, cluttering the Breadboard channel with unrelated messages. Would it be possible to modify the link accordingly? Thank you.

**Comment by Mommotexx** [comment]
Looks like this has been fixed in the newest commit a95aa58

**Comment by Harvester62** [comment]
Perfect, thank you. Than this report can be closed.
