### ISSUE TITLE
LLAMA installation is as slow as hell, alpaca is ok(slow though) on mac m2. How do we solve it?

### ISSUE THREAD

**Issue by samedovzaur** [cocktailpeanut/dalai#205]
![Screenshot 2023-03-22 at 11 56 19](https://user-images.githubusercontent.com/101812544/226851174-11f089f5-1e05-4d2f-a7b9-17d699edf5f8.png)

**Comment by dgauche** [comment]
No longer available now giving a 404 error :-(

**Comment by ItsPi3141** [comment]
> No longer available now giving a 404 error :-(

Well sorry. I took down the llama links.

**Comment by dgauche** [comment]
Any suggestions where I can find an alternative download location? dgauche at gmail.com

**Comment by ItsPi3141** [comment]
> Any suggestions where I can find an alternative download location? dgauche at gmail.com

There is a certain link that still works. Go back to the commits from around March 17 and you'll find them.
