### ISSUE TITLE
No output after submitting prompt

### ISSUE THREAD

**Issue by dotvignesh** [cocktailpeanut/dalai#23]
No errors whatsoever occurred while installing and setting up dalai
But there's no output after submitting the prompt on the Web UI.

7B Model:
<img width="1032" alt="Screenshot 2023-03-13 at 10 10 48 PM" src="https://user-images.githubusercontent.com/19832025/224768188-b0d28287-8ea9-4ef9-b5c5-a6623c358299.png">

Terminal:
<img width="682" alt="Screenshot 2023-03-13 at 9 56 52 PM" src="https://user-images.githubusercontent.com/19832025/224766486-9f8777d2-ba19-4d76-8b09-f3662d937fe7.png">

Browser: 
There seems to be a warning message associated with socket.io
<img width="1440" alt="Screenshot 2023-03-13 at 9 54 16 PM" src="https://user-images.githubusercontent.com/19832025/224767215-4f6ae46c-d011-4c5e-9b3d-268dd8721990.png">

(Running on M1 MacBook Air)

**Comment by 360macky** [comment]
How much does the 7B folder weigh?

**Comment by fermigas** [comment]
Can you list a detailed view of the contents of 7B?   You should see something like this:  

![image](https://user-images.githubusercontent.com/5990101/224789549-a88285ee-0146-4bb1-981b-a40d1b3ae87c.png)

**Comment by dotvignesh** [comment]
<img width="1032" alt="Screenshot 2023-03-13 at 11 49 40 PM" src="https://user-images.githubusercontent.com/19832025/224793899-1cbb6cd9-63c6-48b5-a5c5-437bda3d3abc.png">

I don't seem to have the 4-bit vector quantized bin file 🤔

Tried reinstalling dalai and redownloading the models a couple of times though

**Comment by dotvignesh** [comment]
> fermigas

Around 27GB

**Comment by dotvignesh** [comment]
> How much does the 7B folder weigh?

Around 27GB

**Comment by dotvignesh** [comment]
> How much does the 7B folder weigh?

Around 27 GB

But just figured this out, apparently there is this error stating `Illegal instruction: 4` which I failed to notice
<img width="682" alt="Screenshot 2023-03-13 at 11 53 35 PM" src="https://user-images.githubusercontent.com/19832025/224795290-5838aeb1-584d-4952-a680-446b8034aee9.png">

**Comment by fermigas** [comment]
@dotvignesh  illegal instruction 4  means your binaries contain instructions the OS you are trying to run them under doesn't understand.   For some reason when "quantize" was built on your machine, it might have been built for Intel silicon instead of the Apple silicon M1 you have.   

I'm not sure how to fix it, but maybe this will help someone else who does.

**Comment by theRichu** [comment]
https://github.com/ggerganov/llama.cpp/issues/41#issuecomment-1465163026

this comment works!

> > 7B 폴더의 무게는 얼마입니까?
> 
> 약 27GB
> 
> 그러나 방금 이것을 알아냈고, 분명히 `Illegal instruction: 4`내가 눈치채지 못한 오류가 있다는 것을 <img alt="스크린샷 2023-03-13 오후 11 53 35" width="682" src="https://user-images.githubusercontent.com/19832025/224795290-5838aeb1-584d-4952-a680-446b8034aee9.png">

**Comment by dotvignesh** [comment]
Re-installing command line tools worked for me, thank you folks!!
