### ISSUE TITLE
'dalai' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Shaan-kapoor** [cocktailpeanut/dalai#232]
```
C:\Users\shaan>npx dalai llama install 7B
'dalai' is not recognized as an internal or external command,
operable program or batch file.


```
node.js and python are installed already

**Comment by MarlinMr** [comment]
Can you do `npx` and show the result from that?

**Comment by mooggsentry** [comment]
I have the same issue. 

> 
> C:\Users\XXXXX>npx dalai alpaca install 7B
> 'dalai' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\XXXXXX>npx
> 
> Entering npm script environment at location:
> C:\Users\XXXXXX
> Type 'exit' or ^D when finished
> 
> Microsoft Windows [Version 10.0.19044.2728]
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Users\XXXXX>

**Comment by lszoszk** [comment]
Change the directory to the one where you have dalai files. If this doesn't help, try the following: npm install dalai alpaca 7b.

**Comment by mooggsentry** [comment]
> Change the directory to the one where you have dalai files. If this doesn't help, try the following: npm install dalai alpaca 7b.

npm install dalai alpaca 7b worked for me
