### ISSUE TITLE
Is Spanish language available for this?

### ISSUE THREAD

**Issue by ZetDeveloper** [cocktailpeanut/dalai#238]
Hello, I would like to know if this project supports Spanish language. I have reviewed the documentation and README file, but couldn't find any information about the availability of Spanish language. It would be great to know if there is any plan or roadmap to implement Spanish language in this application. Thank you very much for your time and we look forward to your response.

**Comment by userbox020** [comment]
Brother, solo hay 19 contribuidores en el proyecto, y solo 63 personas estan siguiendo el repo, cuantas de esas personas hablaran español y estaran interesadas en hacer un plan o roadmap en español para implementar "Spanish language in this application"?
Si quieres hacemos un grupo de habla hispana y empezamos a planear como trabajar y podemos hacer una propuesta al admin.

**Comment by ZetDeveloper** [comment]
Pero los modelos están en español ?

**Comment by ZetDeveloper** [comment]
Se puede preguntar en español?

**Comment by userbox020** [comment]
Lo más seguro es que LlaMa si te contesté en español con los mismos errores que vienen mencionando en los issues del repo. Por otro lado alpaca no creo pero igual no se pierde nada preguntándole.

**Comment by deikka** [comment]
Alpaca responde, pero de manera muy poco acertada y sólo si el system prompt está en español.

**Comment by stevecode21** [comment]
Me apunto a la idea de trabajar en conjunto para dar un support más robusto en español.
