### ISSUE TITLE
The repository's main image(and title JUST RUN THIS) are a bit misleading for windows users

### ISSUE THREAD

**Issue by rupakhetibinit** [cocktailpeanut/dalai#242]
The repository requires much of visual studio installed to get it running on windows but it doesn't tell it upfront and claims it's only 2 commands away from running the llama models whereas in reality you get to the windows setup after scrolling quite a bit to the bottom part. 
~~A lot of the issues I've seen that are opened are just because of the claim of two commands only, leading to bunch errors on windows~~  I'd suggest a better title at least written with something like 

# JUST RUN THIS(On linux and mac)
## !!!IMPORTANT For windows you need to have visual studio, scroll below for information

This is a lot better ~~which will cause less errors for people~~, because not everyone has visual studio installed particularly with MSVC as well. 

I don't think I found any open issues for something like this. Maybe I missed it. If it has already been suggested, feel free to close this issue.

**Comment by Tomat0r** [comment]
May also need to add the fact that you need to run visual studio once for it to install all of the dependencies. I was stuck on that for a long time.
