### ISSUE TITLE
llama_model_load: loading model from 'models/7B/ggml-model-q4_0.bin'

### ISSUE THREAD

**Issue by jethro254wt** [cocktailpeanut/dalai#251]
![image](https://user-images.githubusercontent.com/128108848/227429457-c40f4162-76e4-40dd-8b3f-5a61a95fa1f8.png)

![image](https://user-images.githubusercontent.com/128108848/227429401-6ef62063-f69e-4607-a350-7913b9ae23dc.png)

Inside my "dalai\alpaca\models\7B" folder I just have 3 files "checklist.chk" "consolidated.00.pth" and "params.json". I really do more with Java and web development so I'm very out of my league. I assume I'm missing some files, but any help would be greatly appreciated!

**Comment by Theknight2015** [comment]
I have the same problem on my 30B and 65B installations.

30B Installation Directory
- checklist.chk
- consolidated.00.pth
- consolidated.01.pth
- consolidated.02.pth
- consolidated.03.pth
- params.json

65B Installation Directory
- checklist.chk
- consolidated.00.pth
- consolidated.01.pth
- consolidated.02.pth
- consolidated.03.pth
- consolidated.04.pth
- consolidated.05.pth
- params.json

I'm not experienced in this area to know what to do with these. I found the ./quantize tutorial [here](https://github.com/cocktailpeanut/dalai/issues/241) for 7B and 13B because I keep getting a error of - './quantize' is not recognized as the name of a cmdlet, function, script file, or operable program - so I used [this](https://github.com/cocktailpeanut/dalai/issues/241#:~:text=I%20just%20fixed,alpaca%20on%20windows) tutorial to quantize those files but I don't have the files needed in my 30B and 65B directories so I can't run those.

Any help or guidance would be appreciated. Thanks!

**Comment by can-er** [comment]
Same issue here - on Mac Ventura 13.0.1 I have this error message : 
```bash
make -j && ./main -m ./models/7B/ggml-model-q4_0.bin -p "Building a website can be done in 10 simple steps:" -n
Makefile:24: Your arch is announced as x86_64, but it seems to actually be ARM64. Not fixing that can lead to bad performance. For more info see: https://github.com/ggerganov/whisper.cpp/issues/66#issuecomment-1282546789
sysctl: unknown oid 'machdep.cpu.leaf7_features'
I llama.cpp build info: 
I UNAME_S:  Darwin
I UNAME_P:  i386
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mf16c -DGGML_USE_ACCELERATE
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:   -framework Accelerate
I CC:       Apple clang version 14.0.0 (clang-1400.0.29.202)
I CXX:      Apple clang version 14.0.0 (clang-1400.0.29.202)
```

**Comment by jethro254wt** [comment]
So Following the directions in the ReadMe, I got it working in terminal which honestly is good enough for me! 

Directions:
# Alpaca.cpp

Run a fast ChatGPT-like model locally on your device. The screencast below is not sped up and running on an M2 Macbook Air with 4GB of weights. 


[![asciicast](screencast.gif)](https://asciinema.org/a/dfJ8QXZ4u978Ona59LPEldtKK)


This combines the [LLaMA foundation model](https://github.com/facebookresearch/llama) with an [open reproduction](https://github.com/tloen/alpaca-lora) of [Stanford Alpaca](https://github.com/tatsu-lab/stanford_alpaca) a fine-tuning of the base model to obey instructions (akin to the [RLHF](https://huggingface.co/blog/rlhf) used to train ChatGPT) and a set of modifications to [llama.cpp](https://github.com/ggerganov/llama.cpp) to add a chat interface. 

## Get Started (7B)

Download the zip file corresponding to your operating system from the [latest release](https://github.com/antimatter15/alpaca.cpp/releases/latest). On Windows, download `alpaca-win.zip`, on Mac (both Intel or ARM) download `alpaca-mac.zip`, and on Linux (x64) download `alpaca-linux.zip`. 

Download `ggml-alpaca-7b-q4.bin` and place it in the same folder as the `chat` executable in the zip file. There are several options: 

Once you've downloaded the model weights and placed them into the same directory as the `chat` or `chat.exe` executable, run:

```
./chat
```

The weights are based on the published fine-tunes from `alpaca-lora`, converted back into a pytorch checkpoint with a [modified script](https://github.com/tloen/alpaca-lora/pull/19) and then quantized with llama.cpp the regular way. 

## Building from Source (MacOS/Linux)


```sh
git clone https://github.com/antimatter15/alpaca.cpp
cd alpaca.cpp

make chat
./chat
```


## Building from Source (Windows)

- Download and install CMake: <https://cmake.org/download/>
- Download and install `git`. If you've never used git before, consider a GUI client like <https://desktop.github.com/>
- Clone this repo using your git client of choice (for GitHub Desktop, go to File -> Clone repository -> From URL and paste `https://github.com/antimatter15/alpaca.cpp` in as the URL)
- Open a Windows Terminal inside the folder you cloned the repository to
- Run the following commands one by one:

```ps1
cmake .
cmake --build . --config Release
```

- Download the weights via any of the links in "Get started" above, and save the file as `ggml-alpaca-7b-q4.bin` in the main Alpaca directory.
- In the terminal window, run this command:
```ps1
.\Release\chat.exe
```
- (You can add other launch options like `--n 8` as preferred onto the same line)
- You can now type to the AI in the terminal and it will reply. Enjoy!

## Credit

This combines [Facebook's LLaMA](https://github.com/facebookresearch/llama), [Stanford Alpaca](https://crfm.stanford.edu/2023/03/13/alpaca.html), [alpaca-lora](https://github.com/tloen/alpaca-lora) and [corresponding weights](https://huggingface.co/tloen/alpaca-lora-7b/tree/main) by Eric Wang (which uses [Jason Phang's implementation of LLaMA](https://github.com/huggingface/transformers/pull/21955) on top of Hugging Face Transformers), and [llama.cpp](https://github.com/ggerganov/llama.cpp) by Georgi Gerganov. The chat implementation is based on Matvey Soloviev's [Interactive Mode](https://github.com/ggerganov/llama.cpp/pull/61) for llama.cpp. Inspired by [Simon Willison's](https://til.simonwillison.net/llms/llama-7b-m2) getting started guide for LLaMA. [Andy Matuschak](https://twitter.com/andy_matuschak/status/1636769182066053120)'s thread on adapting this to 13B, using fine tuning weights by [Sam Witteveen](https://huggingface.co/samwit/alpaca13B-lora). 


## Disclaimer

Note that the model weights are only to be used for research purposes, as they are derivative of LLaMA, and uses the published instruction data from the Stanford Alpaca project which is generated by OpenAI, which itself disallows the usage of its outputs to train competing models.

**Comment by OGBeas222** [comment]
> I have the same problem on my 30B and 65B installations.
> 
> 30B Installation Directory
> 
> * checklist.chk
> * consolidated.00.pth
> * consolidated.01.pth
> * consolidated.02.pth
> * consolidated.03.pth
> * params.json
> 
> 65B Installation Directory
> 
> * checklist.chk
> * consolidated.00.pth
> * consolidated.01.pth
> * consolidated.02.pth
> * consolidated.03.pth
> * consolidated.04.pth
> * consolidated.05.pth
> * params.json
> 
> I'm not experienced in this area to know what to do with these. I found the ./quantize tutorial [here](https://github.com/cocktailpeanut/dalai/issues/241) for 7B and 13B because I keep getting a error of - './quantize' is not recognized as the name of a cmdlet, function, script file, or operable program - so I used [this](https://github.com/cocktailpeanut/dalai/issues/241#:~:text=I%20just%20fixed,alpaca%20on%20windows) tutorial to quantize those files but I don't have the files needed in my 30B and 65B directories so I can't run those.
> 
> Any help or guidance would be appreciated. Thanks!

where i can find most powerful models for alpaca.cpp ?
