### ISSUE TITLE
Run the Alpaca model?

### ISSUE THREAD

**Issue by cktang88** [cocktailpeanut/dalai#27]
Is there a way to run Alpaca using this?

https://github.com/tatsu-lab/stanford_alpaca

**Comment by fermigas** [comment]
They don't seem to be releasing the weights, probably because they're using the research weights from Meta.   They are releasing the instruct dataset and the code they used to generate it.  There's no code to fine tune LLaMA with the data, though.

**Comment by distbit0** [comment]
Someone is developing an open source implementation of the alpaca training code: https://github.com/tloen/alpaca-lora

Costs < $100 to train, now that the instructions used are public (which cost ~$500 to generate using gpt3-davinci-003

**Comment by fermigas** [comment]
![image](https://user-images.githubusercontent.com/5990101/225131615-67179ee5-fd65-4ad7-8840-26070937afd1.png)

**Comment by dsernst** [comment]
The alpaca-lora 7b weights were published: https://huggingface.co/tloen/alpaca-lora-7b/tree/main

**Comment by justinh-rahb** [comment]
@dsernst I'm definitely exposing my lack of understanding of the field (but I do want to learn): how do I merge those weights with the ones I've already got?

**Comment by ldubost** [comment]
Maybe this project could help: https://github.com/antimatter15/alpaca.cpp

**Comment by totoCZ** [comment]
Either we have to merge code from alpaca's chat.cpp back to the original main.cpp so it runs non-interactively and works with dalai
Or we need to modify dalai so it can run the executable in chat mode
Maybe adding special handling in dalai is better until llama.cpp adds support for faster model reloading
I could probably hack it together just for myself but I don't want to duplicate work

**Comment by cktang88** [comment]
is this closed by https://github.com/cocktailpeanut/dalai/commit/a4cbf1c73c968aefd1c51c04fb3221717780e306 ?

**Comment by justinh-rahb** [comment]
Seems so. Got everything working now, very nice!

**Comment by bleriot14** [comment]
So, Does Dalai's Alpaca work like https://github.com/antimatter15/alpaca.cpp now ? I want use Dalai's Alpaca with chat mode, not autocomplete mode. Did you find the solution ?
