### ISSUE TITLE
windows 10 issue getting the alpaca model to work

### ISSUE THREAD

**Issue by ramzeez88** [cocktailpeanut/dalai#286]
have everything istalled as required but still when run the local server and enter my prompt i don't get any answers and cmd is showing this :
C:\Users\Adam>npx dalai serve
mkdir C:\Users\Adam\dalai
Server running on http://localhost:3000/
> query: { method: 'installed', models: [] }
modelsPath C:\Users\Adam\dalai\alpaca\models
{ modelFolders: [ '7B' ] }
exists 7B
modelsPath C:\Users\Adam\dalai\llama\models
{ modelFolders: [] }
> query: { method: 'installed', models: [] }
modelsPath C:\Users\Adam\dalai\alpaca\models
{ modelFolders: [ '7B' ] }
exists 7B
modelsPath C:\Users\Adam\dalai\llama\models
{ modelFolders: [] }
> query: {
  seed: -1,
  threads: '8',
  n_predict: '200',
  top_k: 40,
  top_p: 0.9,
  temp: '0.1',
  repeat_last_n: 64,
  repeat_penalty: 1.3,
  debug: true,
  models: [ 'alpaca.7B' ],
  prompt: 'what is\n',
  id: 'TS-1679857046233-72254'
}
C:\Users\Adam\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (C:\Users\Adam\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:219:35)
    at Socket.<anonymous> (C:\Users\Adam\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\dalai\index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\Adam\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Adam\AppData\Local\npm-cache\_npx\3c737cbb02d79cc9\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.15.0

what could be the problem here ?

**Comment by jojojoy99** [comment]
I have the same issue

**Comment by ramzeez88** [comment]
got it working. i erased all the webbrowser history and ran it again :)
