### ISSUE TITLE
Autocomplete not working due to Socket.io issues

### ISSUE THREAD

**Issue by areibman** [cocktailpeanut/dalai#3]
## Description
Running the server with `npx dalai serve` and clicking "autocomplete" doesn't work
## Expected Behavior
Clicking autocomplete after typing in text leads to nothing happening.

## Actual Behavior
![2023-03-12 17 18 44](https://user-images.githubusercontent.com/14807319/224583177-61ab70cf-3c93-4b84-a3b3-dc96bf4fef9d.gif)

Nothing renders on page. There's a suspicious error in console about socket.io
Console error:
`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/socket.io.min.js.map`

## Possible Solution
[If you have an idea for how to fix the issue, describe it here.]

## Steps to Reproduce
1. `npx dalai llama`
2. `npx dalai serve`
3. Try to use autocomplete (and fail).

## Environment
Running on an M1 MBP. Tried Safari and Chrome on `localhost:3000`

- OS: MacOS Ventura
- Browser: Safari/Chrome
- Version: 

## Screenshots
<img width="507" alt="image" src="https://user-images.githubusercontent.com/14807319/224583311-e2620ea4-0765-4f32-9d14-d3a9e88b1916.png">

## Labels
- bug

**Comment by imohitmayank** [comment]
Okay, so here is how it worked for me. I checked (Mac - `/Users/me/dalai/models`) and it seems the model was not downloaded (missing chk files). I downloaded it again (using `npx dalai llama 7B`) and then this time `npx dalai serve` worked.

**Comment by marcuswestin** [comment]
This is fixed in #16, which prints an error message if the model does not exist
