### ISSUE TITLE
How to run dalai on GPU for improved performance and reduced CPU usage

### ISSUE THREAD

**Issue by RaposaRale** [cocktailpeanut/dalai#306]
First: You need a Python environment with CUDA-enabled PyTorch installed. To install CUDA-enabled PyTorch, simply run this command:

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
Source: https://pytorch.org/

Second: You should install the compatible CUDA toolkit version 11.7 and the corresponding cuDNN library (if you don't know how, there are several tutorials on YouTube).

Third: Test your environment to see if your GPU is operational with PyTorch by running:

python -c "import torch; print(torch.cuda.is_available())"
Fourth: You must move the folder of your Python environment to the dalai environment folder, then run the same test with PyTorch inside the new dalai environment:

python -c "import torch; print(torch.cuda.is_available())"
The response should be True.

**Comment by RiccaDS** [comment]
Is 11.7 necessary? I'm on old hardware and can't go up to 11.7
