### ISSUE TITLE
Installation terminated without any error

### ISSUE THREAD

**Issue by forestbat** [cocktailpeanut/dalai#336]
I run command on my computer(before this I have installed Visual Studio)：
```
C:\Users\PC303>npx dalai llama install 13B
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) y

C:\Users\PC303>
```
Yes，when after I installing `dalai 0.3.1`，the program terminated，and I can ensure I used cmd to do this.
So how to solve it？

**Comment by VanHallein** [comment]
Please make sure to have Visual Studio with C++, Python, and NodeJS support installed. Also, additional install Node.js version 18.5 on your computer. Having both installed will cause some compiling lines etc. In your console output. It will take a couple of minutes to build and download the model. I tested this under W10 22H2.

**Comment by forestbat** [comment]
@VanHallein My node.js version is 19.1，and I have these 3 supports in my computer.
When I try to run `npx dalai serve`，there is no page in my explorer.

**Comment by bendeguzszkalka** [comment]
I have this too. I use wsl Debian, my nodejs is at v18.13.0, npm at 9.2.0, and python at 3.11.2. I have tried the troubleshooting steps, but still nothing happens.

**Comment by VanHallein** [comment]
As far as I am informed, you guys need to stick with Python 3.10 and Node.js 18.5. Can you guys downgrade and try again? Also, empty page happened to me on Firefox, but working fine with Chrome. Have you tried?

**Comment by mmcc1** [comment]
I have:

Windows Server 2019 Standard v.1809
Ubuntu-22.04
Python 3.10.10
Node 18.5

Install loops, never installs on both OSs.  

C:\>npx dalai llama install 7B
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y)

C:\>npx dalai serve
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y)

**Comment by bendeguzszkalka** [comment]
> As far as I am informed, you guys need to stick with Python 3.10 and Node.js 18.5. Can you guys downgrade and try again? Also, empty page happened to me on Firefox, but working fine with Chrome. Have you tried?

It still does not work. The issue is not that the page is blank, the program just closes after running the command. Nothing starts at localhost:3000 and the program does not write out any errors or anything.

```shell
$ npx dalai serve
Need to install the following packages:
  dalai@0.3.1
Ok to proceed? (y) y
``` 
Nothing happens after this.

**Comment by soltaniworld** [comment]
I am having the same issue, and I noticed that the ~/dalai/ folder is empty.

**Comment by bendeguzszkalka** [comment]
> I am having the same issue, and I noticed that the ~/dalai/ folder is empty.

I have the venv folder in it.

**Comment by thebaldgeek** [comment]
Same issue.
Win 11.
Node 18.5 
Python3.10.10
Installed VS and ensured I checked the three boxes and rebooted.

After saying 'y' to the 2 steps a short series of downloads occur and then back to the prompt.
The server never starts, there is a timeout  on port 3000.

Update: I found that Python was not in the path after the VS install and reboot.
Going to Python website and running the installer from there being sure to add python to path makes the model install work.
Now getting a crash error after asking a single prompt, will open a new issue for this error.

**Comment by 64jcl** [comment]
I never got the llama model to work, but alpaca 13B works fine. The cpp file tries to call main.exe which the llama build process does not generate (it makes a llama.exe file instead) - but the alpaca one generates the main.exe and runs fine when served.

**Comment by MrAnayDongre** [comment]
For alpaca 7B model you can follow the [link](https://github.com/antimatter15/alpaca.cpp).
This is the only direct download I could find.

**Comment by Griffin23** [comment]
Try `npm i dalai -g` to install dalai. Then fix the errors output at console.

In my case, it said there is no visual studio c++ package (Sorry I don't remember that clearly). So I install the vs c++ package firstly via visual studio installer.

Then will come the second error said that there is no any Windows SDK. And I open the visual studio installer, go to the c++ part, check the optional checkbox to select a Win10 SDK and install.

![image](https://github.com/cocktailpeanut/dalai/assets/5829649/16017521-fc79-465f-b6fd-860db096eeab)

Then I can install dalai successfully. And after run `npx dalai serve`, I can start the app.
