### ISSUE TITLE
Linux installer is apt-centric

### ISSUE THREAD

**Issue by Ashvith10** [cocktailpeanut/dalai#358]
It would be better if the build process wasn't hard coded only for `apt` - would be better to list down dependencies to install manually. Running this on other Linux distro is not easy.

**Comment by Ironlenny** [comment]
Yes, the package should just try to compile, and return an error with a list of dependencies if it cannot. It is security threat to have a non-system package changing the base system. I certainly don't want *any* npm package mucking around with my system.

Edit: And `index.js` is calling `pip`! Why is `index.js` doing any install? *Anything* that needs to be setup or installed outside of package should be left up to the user. It's just a basic packaging principle that the user knows her system best. Any time you're calling *another* package manager, especially when passing it `-y`, that should be instructions in the README instead.

If you really want to automate all of it, it should be in a shell script that is kept outside the package.

**Comment by erezsh** [comment]
Even on Ubuntu, if you don't have venv installed, it fails with a cryptic error, and only works after you apt install venv manually.
