### ISSUE TITLE
Why the repository is named “dalai”？

### ISSUE THREAD

**Issue by forestbat** [cocktailpeanut/dalai#366]
I'm a Chinese developer and “dalai llama” hears like “ta-la-Bla-ma”/“dalai lama” which escaped from China's Tibet，and the name may bring some trouble in China.
So I want to know why you call this repo “dalai”？

**Comment by taf2** [comment]
You should ask ChatGPT

**Comment by Nocturna22** [comment]
Dalai is called Dalai, because LLama is named LLama. If the Chinese government has a problem with it, then it is the Chinese government's problem and the citizens should think about why that is.

**Comment by zhangyun** [comment]
If you search for what "llama" is, you will be happy to call dalai that every day. lol

**Comment by jackccrawford** [comment]
This is where language is fun.  LLAMA is a Spanish word for the familar animal. It's pronounced "yama" in Spanish.  Dalai could be pronounced as "dol a i"  as in AI.
So we could call this repository: "Cocktail Peanuts's Doll Artificial Intelligence Large Language Model Meta Artificial Intelligence"
