### ISSUE TITLE
Problem Model --> query: { prompt: '/stop', models: [] }

### ISSUE THREAD

**Issue by Anubiiiiiiiiiis** [cocktailpeanut/dalai#381]
Hello everyone, 
I installed everything on Windows but I continue to have problems, the localhost page loads it for me but there is nothing inside the models menu.. (is empty)

I downloaded the 65B model separately, then manually inserted it into the c:/users/nameuser/Dalai/llama/models/ and it looks fine

I send the screenshot but when i try to do something there is this error:

![image](https://user-images.githubusercontent.com/130409955/231009164-4b18e376-c9a1-4b18-8491-156017d15b63.png)

or other error:
![image](https://user-images.githubusercontent.com/130409955/231009389-4ce254d7-ebc5-4cb6-9c31-cd8037ba1e8b.png)

How it's wrong? I would like to use 65B locally

**Comment by bendeguzszkalka** [comment]
I think the install urls in the scripts are broken, only the 7B alpaca model works for me.

**Comment by Anubiiiiiiiiiis** [comment]
I understand... but i followed the github guide, and how i can use 65B?

What's the problem..? maybe i can try with 7B first but I would like to use 65B 

I must install the model from cmd necessarily ?

**Comment by Anubiiiiiiiiiis** [comment]
Now i have install correctly the model and i have quantize it,
But..

The problem persist when i write the first prompt:
![image](https://user-images.githubusercontent.com/130409955/231274132-83518508-4aa4-413a-9887-8bb6f0ae3efe.png)


How it's possible?

How i can fix it?

Please help me

**Comment by Anubiiiiiiiiiis** [comment]
I have solved with:
C:\Users\NameUser\dalai\llama\build\bin\Release\quantize.exe C:\Users\NameUser\dalai\llama\models\7B\ggml-model-f16.bin C:\Users\NameUser\dalai\llama\models\7B\ggml-model-q4_0.bin 2

The model was loaded correctly but... now i have this problem , it's work in google chrome INCOGNITO mode
When i put the prompt, the response give me a error:
![image](https://user-images.githubusercontent.com/130409955/231281264-7bca5cc9-6fa0-4244-9608-e86029041397.png)


How i can fix it?

Please help me
