### ISSUE TITLE
Windows Installation Error

### ISSUE THREAD

**Issue by ffreality** [cocktailpeanut/dalai#439]
Windows installation gives this error

```
./quantize : The term './quantize' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:96
+ ... sole]::InputEncoding=[System.Text.Encoding]::UTF8; ./quantize C:\User ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./quantize:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by doktorpetter** [comment]
I am having the same problem when trying to install llama 7B and 13B models. As I am installing the models to a different drive, I use the command "npx dalai llama install 7B --home [path to folder on different drive]" (similar for 13B). The command is typed into cmd on a Win11 machine, Node is v18.16.0, python 3.10.11 and downloaded the latest Visual Studio CE from Microsoft with the checkmarks as instructed.

**Comment by giorgiogiudice** [comment]
same here

**Comment by avidwriter** [comment]
also getting the same error

**Comment by Flip-Reset** [comment]
I also received this error. Using model 'wizardLM-7B.ggml.q4_0'

**Comment by mirek190** [comment]
Why you even bother that obsolete project and stone age models ;)

**Comment by ffreality** [comment]
> Why you even bother that obsolete project and stone age models ;)

personally I am not an AI/NLP developer. I can't say which technology is old and which one is new. I am an Unreal Engine and C++ based virtual reality developer and I want to use NLP technologies on my AR/VR factory simulation products. Especially for question asking based on long texts. But current online services generally train a public model and most of my customers (factories) don't want to share their know-how level technical documentations with some AI tools for the sake of some suggestions.

Even if I solve this problem, I couldn't find any Turkish library which at least 30B parameters (I can access powerful computers) and I don't want to hassle with creating my own dataset. So, I abondened local GPT solutions and use Microsoft Cognitive like AI solutions which can create unique instance for their enterprise customers.

**Comment by floatas** [comment]
I also get this error, fix should be simple, file is just in another folder. I believe there was a change in some visual studio version, and binaries are placed in other locations.

Replace FULL path with your path and run this in CMD:

[System.Console]::OutputEncoding=[System.Console]::InputEncoding=[System.Text.Encoding]::UTF8; <FULLPATH>dalai\llama\build\bin\Release\quantize.exe <FULLPATH>dalai\llama\models\7B\ggml-model-f16.bin <FULLPATH>\dalai\llama\models\7B\ggml-model-q4_0.bin 2

Application expects binaries to be in build\Release folder but instead all binaries are in build\bin\Release.


But even with this fix I get another error, this time when trying to query from web:

Server running on http://localhost:3000/
> query: { method: 'installed', models: [] }
modelsPath dalai\alpaca\models
{ modelFolders: [] }
modelsPath dalai\llama\models
{ modelFolders: [ '7B' ] }
exists 7B
> query: {
  seed: -1,
  threads: 4,
  n_predict: 200,
  top_k: 40,
  top_p: 0.9,
  temp: 0.8,
  repeat_last_n: 64,
  repeat_penalty: 1.3,
  debug: false,
  models: [ 'llama.7B' ],
  prompt: 'what is the capital of france ?',
  id: 'TS-1684429793592-57850'
}
<FULLPATH>dalai-main\index.js:219
    let [Core, Model] = req.model.split(".")
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Dalai.query (<FULLPATH>dalai-main\index.js:219:35)
    at Socket.<anonymous> (<FULLPATH>dalai-main\index.js:534:20)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (<FULLPATH>dalai-main\node_modules\socket.io\dist\typed-events.js:69:22)
    at <FULLPATH>dalai-main\node_modules\socket.io\dist\socket.js:703:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.15.0

**Comment by floatas** [comment]
![image](https://github.com/cocktailpeanut/dalai/assets/7883111/4edf5585-f3e3-495e-bb9a-aba8f681177d)
same with docker on windows 10

**Comment by mirek190** [comment]
I think much easier is to use LLAMA.cpp which is very fast comparing to dalai or kobold.cpp

**Comment by BlueStacksGaming** [comment]
Completed ? where is the solution?
