### ISSUE TITLE
Can't install on different Windows drive

### ISSUE THREAD

**Issue by pax** [cocktailpeanut/dalai#62]
Tried to install it (ran npx) while on the D drive, that's where I have enough space for the larger models.
I got `cd : Cannot find path 'D:\devbox\llama\llama' because it does not exist.`

![llama Screenshot 2023-03-16 155623](https://user-images.githubusercontent.com/116795/225640488-cc0e5b1d-7309-49d3-9d67-078c1590a464.png)

**Comment by corgiz4lif** [comment]
That may be cause you are already in a directory called llama, is there a folder within the first llama folder also called llama?

**Comment by tw9mini** [comment]
I did the same, also on a D: drive, the download started but it's downloading into my user profile on drive C: anyway.
How to convince npx to download the models to the D: drive?
I'm using nvm.

**Comment by pax** [comment]
I guess this is a known issue, see this [todo list published on HN](https://news.ycombinator.com/item?id=35129424):
-   *path:* customize the home directory (instead of automatically storing to $HOME)

**Comment by VictorZakharov** [comment]
Much needed feature, I have a dedicated drive for all of my AI stuff. It's excluded from backup. Main drive is backed up.

**Comment by andresdelcampo** [comment]
You can get around that with --home

Check this issue for manual downloads, etc, -in a different drive- https://github.com/cocktailpeanut/dalai/issues/78

and then something like 

`npx dalai serve --home e:\Models\dalai`

-though for some reason even though it detects the higher models it only shows the 7B ones in the dropdown... damn.
