### ISSUE TITLE
Gets stuck at "Need to install the following packages: dalai@0.2.28"

### ISSUE THREAD

**Issue by eff-coding** [cocktailpeanut/dalai#90]
Hi all, I get stuck at the following message when I try to install either 'alpaca' or 'llama': "Need to install the following packages: dalai@0.2.28". The system asks me "Ok to proceed? (y)",  I accept and it seems to install.  When I re-run the 'alpaca' and 'llama' installer it gos back to the above message. I am on a Mac M1 Max. Any suggestions?

**Comment by edkempx** [comment]
Do you have node version 18 installed?

**Comment by eff-coding** [comment]
@par5er solution did work for me. Thnx a lot.
